services:
  - type: worker
    name: telegram-oil-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python botCom.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
